document.write(''
  + '<!--TEMPLATE STYLE SHEETS -->' 
  + '<link rel ="stylesheet" type="text/css" href="../common/css/style.css" title="style" />'
  + ''   
  + '<!-- SCRIPTS FOR JQUERY TABS & ACCORDION -->' 
  + '<script type="text/javascript" src="../common/scripts/jquery.min.js"></script>'
  + '<script type="text/javascript" src="../common/scripts/jquery-ui.min.js"></script>'
  + '<script type="text/javascript" src="../common/scripts/tabs.js"></script>' 
  + ''
  + '<!-- SCRIPTS FOR LIBRARY FUNCTIONS -->'
  + '<script type="text/javascript" src="../common/scripts/jslib.js"></script>'
  + '<script type="text/javascript" src="../common/scripts/btnpermlogic.js"></script>'   
  + ''
  + '<!--MENU JAVASCRIPT FILES -->' 
  + '<script type="text/javascript" src="../common/scripts/menuslider.js"></script>'
  + '<script type="text/javascript" src="../common/outline/cdptree.js"></script>'  
  + '<script type="text/javascript" src="../common/outline/metree.js"></script>'
  + '');
