document.write(''
  + '<div style="clear: both;"></div>' 
  + ''    
  + '    	<div id="footer">'
  + '    		<div id="footer-container">'
  + '    			<p>Copyright &copy; 2013-2016 <a id="cdp-link" href="http://www.cdp.com/" title="Visit Columbia Data Products on the Web">Columbia Data Products</a>. All rights reserved.</p>'
  + '    		</div>'
  + '    	</div>'
  + ''								
  + '	</div><!--End Primary-->'
  + ''      
  + '</div><!--End Page-->'
  + '');