document.write(''
  + '<div style="clear: both;"></div>' 
  + ''    
  + '    	<div id="footer">'
  + '    		<div id="footer-container">'
  + '    			<p>Copyright &copy; 2013-2015 Columbia Data Products. All rights reserved.</p>'
  + '    		</div>'
  + '    	</div>'
  + ''								
  + '	</div><!--End Primary-->'
  + ''      
  + '</div><!--End Page-->'
  + '');