document.write(''
  + '<div id="page">'
  + ''  
  + '  <div id="header">'
  + '	<div id="header-container">'
  + '		<div id="logo">'
  + '			<img src="../common/media/snapback-apps-logo.png" alt="SnapBack Apps" />'
  + '		</div>'
  + ''
  + '		<div id="app_title">'
  + '');