document.write(''
  + '<div id="page">'
  + '<nav id="menu" class="panel" role="navigation">'
  + ''  
  + '	<div class="logo">'
  + '		<a href="../welcomeoca/main.html" title="Return to the SnapBack Apps Home Page"><img src="../common/media/snapback-apps-logo-open.png" /></a>'  
  + '	</div><!--End Logo-->'
  + ''
  + '	<div class="menu-collapse">'
  + '		<a href="#menu" class="menu-link" title="Click to Close the Navigation">&lArr; Collapse</a>'
  + '	</div>'
  + ''
  + '	<div style="clear: both;"></div>'
  + ''
  + '	<div id="secondary">'
  + '		<div id="treemenu01" tabindex="0">'
  + '');