document.write(''
  + '	</div>'
  + '		</div><!--End Secondary-->'
  + ''
  + '	<div class="help-snapback"><a href="../welcomeoca/main.html" title="Click to Learn How You Can Help SnapBack Apps">'
  + '		<span class="help-snapback-header"><img src="../common/media/we-need-you.png" alt="We Need You" />We Need You</span>'
  + '		<p class="help-snapback-text">Help make SnapBack Apps by contributing and improving the experience for other users.</p>'
  + '	</a></div><!--End .help-snapback-->'
  + ''
  + '</nav>'
  + ''
  + '<div id="collapsed-menu">'
  + '	<div class="logo">'
  + '		<a href="../welcomeoca/main.html" title="Return to the SnapBack Apps Home Page"><img src="../common/media/snapback-apps-logo-closed.png" /></a>'  
  + '	</div><!--End Logo-->'
  + ''
  + '	<div class="menu-collapse">'
  + '		<a href="#menu" class="menu-link" title="Click to Expand the Navigation">&rArr;</a>'
  + '	</div>'
  + ''
  + ''
  + '</div>'
  + ''
  + '<div id="primary" class="push">'
  + '');