document.write(''
  + '	</div>'
  + '		</div><!--End Secondary-->'
  + ''
  + ''
  + '</nav>'
  + ''
  + '<div id="collapsed-menu">'
  + '	<div class="logo">'
  + '		<a href="../welcomeoca/main.html" title="Return to the SnapBack Apps Home Page"><img src="../common/media/snapback-apps-logo-closed.png" /></a>'  
  + '	</div><!--End Logo-->'
  + ''
  + '	<div class="menu-collapse">'
  + '		<a href="#menu" class="menu-link" title="Click to Expand the Navigation">&rArr;</a>'
  + '	</div>'
  + ''
  + ''
  + '</div>'
  + ''
  + '<div id="primary" class="push">'
  + '');