document.write(''
  + '<p>Each Committee has signed off on their part.  For more detail of each committees\' policies and procedures, visit their home pages.</p>'
  + ''
  + '<table class="certification-table">'
  + ''
  + '<tr>'
  + '	<th>Certification Committee</th>'
  + '	<th>Certification Details</th>'
  + '</tr>'
  + ''
  + '<tr>'
  + '	<td class="committee-name">CDP Certification</td>'
  + '	<td>'
  + '		<p>Released = [Date] | Version = [Version] | First Released = [Date] | Manifest Name = [Name] | By = [Author/Group]</p>'
  + '		<p>NOTE: CDP will include any notes directed at the user here.</p>'
  + '	</td>'
  + '</tr>'
  + ''
  + '<tr>'
  + '	<td class="committee-name">Performance / System Impact</td>'
  + '	<td>'
  + '		<p>RAM = [Details] | DISK = [Details] | Runtime/CPU = [Details]</p>'
  + '		<p>NOTE: the Performance/System Impact Committee will include any notes directed at the user here.</p>'
  + '	</td>'
  + '</tr>'
  + ''
  + '<tr>'
  + '	<td class="committee-name">Security/Logging/User Rights/Locations</td>'
  + '	<td>'
  + '		<p>Security:[Details]<br />Logging: [Details]<br />Users: [Details]<br />Rights required: [Details]<br />Locations: [Details]<br /></p>'
  + '		<p>NOTE: the Security/Logging/User Rights/Locations Committee will include any notes directed at the user here.</p>'
  + '	</td>'
  + '</tr>'
  + ''
  + '<tr>'
  + '	<td class="committee-name">Safety/Conflicts/Compatibility/Expertise</td>'
  + '	<td>'
  + '		<p>Safe = [Details] | Conflicts = [Details] | Compatibility = [Details] | UserType = [Details]</p>'
  + '		<p>NOTE: the Safety/Conflicts/Compatibility/Expertise Committee will include any notes directed at the user here.</p>'
  + '	</td>'
  + '</tr>'
  + ''
  + '<tr>'
  + '	<td class="committee-name">Legal/Attribution/Liability</td>'
  + '	<td>'
  + '		<p>Attributed = [Details] | DMCA Issues = [Details] | Damage = [Details]</p>'
  + '		<p>NOTE: the Legal/Attribution/Liability Committee will include any notes directed at the user here.</p>'
  + '	</td>'
  + '</tr>'
  + ''
  + '<tr>'
  + '	<td class="committee-name">Monetization/Privacy</td>'
  + '	<td>'
  + '		<p>Monetization = [Details] | Privacy Issues = [Details]</p>'
  + '		<p>NOTE: the Monetization/Privacy Committee will include any notes directed at the user here.</p>'
  + '	</td>'
  + '</tr>'
  + ''
  + '</table>'
  + '');