document.write(''
  + '<div style="clear: both;"></div>'
  + ''								
  + '		</div><!--End Primary-->'
  + ''      
  + '    </div><!--End Content Wrapper-->'
  + ''    
  + '    <div id="footer">'
  + '    	<div id="footer-container">'
  + '    		<p>Copyright &copy; 2013-2015 Columbia Data Products. All rights reserved.</p>'
  + '    	</div>'
  + '    </div>'
  + ''
  + '</div><!--End Page-->'
  + '');